
```
@startuml
scale 1.5
actor Usuario
boundary ViewConsultarRestaurante <<view>>
control RestauranteController <<controller>>
entity RestauranteEntity <<entity>>

== Início ==
Usuario -> ViewConsultarRestaurante : Selecionar "Visualizar Restaurantes"
activate Usuario
activate ViewConsultarRestaurante
ViewConsultarRestaurante -> RestauranteController : visualizarRestaurantes()
activate RestauranteController
RestauranteController --> ViewConsultarRestaurante : listaDeRestaurantes
deactivate RestauranteController

== Seleção ==
Usuario -> ViewConsultarRestaurante : Selecionar "Restaurante"
ViewConsultarRestaurante -> RestauranteController : visualizarDados(restaurante)
activate RestauranteController
RestauranteController -> RestauranteEntity : visualizarDados(restaurante)
activate RestauranteEntity
RestauranteEntity --> RestauranteController : dados
deactivate RestauranteEntity
RestauranteController --> ViewConsultarRestaurante : dados
deactivate RestauranteController
Usuario -> ViewConsultarRestaurante : Selecionar "Avaliar Restaurante"
ViewConsultarRestaurante -> RestauranteController : avaliarRestaurante()
activate RestauranteController
RestauranteController --> ViewConsultarRestaurante : avaliarRestaurante()
deactivate RestauranteController
Usuario -> ViewConsultarRestaurante : Preencher Avaliacao
ViewConsultarRestaurante -> RestauranteController : salvarAvaliacao()
activate RestauranteController
RestauranteController --> ViewConsultarRestaurante : avaliacao
deactivate RestauranteController
Usuario -> ViewConsultarRestaurante : Selecionar "Sair"
deactivate ViewConsultarRestaurante
deactivate Usuario
@enduml
```
