
```
@startuml
scale 1.5
actor Usuario
boundary ViewConsultarRestaurante <<view>>
control RestauranteController <<controller>>
entity RestauranteEntity <<entity>>

== Início ==
Usuario -> ViewConsultarRestaurante : Selecionar "Visualizar Restaurantes"
activate Usuario
activate ViewConsultarRestaurante
ViewConsultarRestaurante -> RestauranteController : visualizarRestaurantes()
activate RestauranteController
RestauranteController --> ViewConsultarRestaurante : listaDeRestaurantes

deactivate RestauranteController

== Seleção ==
Usuario -> ViewConsultarRestaurante : Selecionar "Obter relatorio"
ViewConsultarRestaurante -> RestauranteController : obterRelatorio(restaurante,tipoRelatorio)
activate RestauranteController
RestauranteController -> RestauranteEntity : obterRelatorio(restaurante,tipoRelatorio)
activate RestauranteEntity
RestauranteEntity --> RestauranteController : dados
deactivate RestauranteEntity
RestauranteController --> ViewConsultarRestaurante : ExibirMsg(dados)
deactivate RestauranteController
Usuario -> ViewConsultarRestaurante : Selecionar "Baixar"
ViewConsultarRestaurante -> RestauranteController : baixarRelatorio(dados)
RestauranteController --> ViewConsultarRestaurante : relatorio
Usuario -> ViewConsultarRestaurante : Selecionar "Sair"
deactivate ViewConsultarRestaurante
deactivate Usuario
@enduml
```
