spring.application.name=BuchoCheio
# URL do banco PostgreSQL (local)
spring.datasource.url=jdbc:postgresql://localhost:5432/buchoCheio

# Usuário e senha do PostgreSQL
spring.datasource.username=vini
spring.datasource.password=

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA / Hibernate
# cria/atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
# mostra os comandos SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


